### ISSUE TITLE
Unable to import caffe and apollocaffe in python. After importing caffe successfully, apollocaffe throws an error and vice versa

### ISSUE THREAD

**Issue by jaknap32** [Russell91/ReInspect#21]
Hi,
I installed caffe from http://caffe.berkeleyvision.org/installation.html
and apollocaffe from http://apollocaffe.com/#Installation
both of them got installed properly and get imported in python independently.
but importing apollocaffe after caffe gives this error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jaknap/apollocaffe/python/apollocaffe/__init__.py", line 1, in <module>
    from cpp._apollocaffe import Tensor, ApolloNet, CppConfig, make_numpy_data_param, Blob
  File "/home/jaknap/apollocaffe/python/apollocaffe/cpp/__init__.py", line 1, in <module>
    import _apollocaffe
ImportError: /home/jaknap/apollocaffe/python/apollocaffe/cpp/_apollocaffe.so: undefined symbol: _ZN5caffe5Caffe10singleton_E
```
Following is the environment variable setting:-
```
export PYTHONPATH=$PYTHONPATH:/home/musigma/caffe/python
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/musigma/apollocaffe/build/lib
export PYTHONPATH=$PYTHONPATH:/home/musigma/apollocaffe/python
```
Where am i going wrong? please help!

**Comment by Russell91** [comment]
Please make sure your LD_LIBRARY_PATH does not contain the original caffe's libcaffe.so. Apollocaffe contains it's own caffe version that has slight changes from the original.

**Comment by jaknap32** [comment]
Thanks, Russell for such a quick reply!! :). the LD_LIBRARY_PATH is pointing to the new libcaffe.so inside the apollocaffe folder still no luck, the same error. today will try reinstalling the whole thing.

**Comment by Russell91** [comment]
What is the output of ldd /path/to/_apollocaffe.so?

**Comment by CharlesShang** [comment]
if you use ubuntu, I think you need to add a *apollocaffe.conf*  to /etc/ld.so.conf.d/
```
sudo sh -c 'echo "/path/to/apollocaffe/" > /etc/ld.so.conf.d/apollocaffe.conf'
sudo ldconfig
```

**Comment by jaknap32** [comment]
hey @Russell91 below is the output!
```
	linux-vdso.so.1 =>  (0x00007fff433ac000)
	libglog.so.0 => /usr/lib/x86_64-linux-gnu/libglog.so.0 (0x00007f67c4806000)
	libprotobuf.so.8 => /usr/lib/x86_64-linux-gnu/libprotobuf.so.8 (0x00007f67c4504000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f67c4200000)
	libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007f67c3c9c000)
	libcaffe.so => /home/musigma/apollocaffe/build/lib/libcaffe.so (0x00007f67c377e000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f67c3568000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f67c31a3000)
	libgflags.so.2 => /usr/lib/x86_64-linux-gnu/libgflags.so.2 (0x00007f67c2f83000)
	libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007f67c2d68000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f67c2b4a000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f67c2931000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f67c262b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f67c4c81000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f67c2427000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f67c2224000)
	libleveldb.so.1 => /usr/lib/x86_64-linux-gnu/libleveldb.so.1 (0x00007f67c1fd7000)
	liblmdb.so.0 => /usr/lib/x86_64-linux-gnu/liblmdb.so.0 (0x00007f67c1dc5000)
	libboost_system.so.1.54.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.54.0 (0x00007f67c1bc1000)
	libhdf5_hl.so.7 => /usr/lib/x86_64-linux-gnu/libhdf5_hl.so.7 (0x00007f67c1991000)
	libhdf5.so.7 => /usr/lib/x86_64-linux-gnu/libhdf5.so.7 (0x00007f67c14f5000)
	libopencv_core.so.2.4 => /usr/local/lib/libopencv_core.so.2.4 (0x00007f67c105a000)
	libopencv_highgui.so.2.4 => /usr/local/lib/libopencv_highgui.so.2.4 (0x00007f67c0dca000)
	libopencv_imgproc.so.2.4 => /usr/local/lib/libopencv_imgproc.so.2.4 (0x00007f67c08d2000)
	libboost_thread.so.1.54.0 => /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.54.0 (0x00007f67c06bc000)
	libcblas.so.3 => /usr/lib/libcblas.so.3 (0x00007f67c049b000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f67c0279000)
	libsnappy.so.1 => /usr/lib/libsnappy.so.1 (0x00007f67c0073000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f67bfe6b000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007f67bfc05000)
	libtbb.so.2 => /usr/lib/libtbb.so.2 (0x00007f67bf9d1000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f67bf77c000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f67bf556000)
	libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5 (0x00007f67bf2e4000)
	libjasper.so.1 => /usr/lib/x86_64-linux-gnu/libjasper.so.1 (0x00007f67bf08d000)
	libIlmImf.so.6 => /usr/lib/x86_64-linux-gnu/libIlmImf.so.6 (0x00007f67bedde000)
	libHalf.so.6 => /usr/lib/x86_64-linux-gnu/libHalf.so.6 (0x00007f67beb9b000)
	libdc1394.so.22 => /usr/lib/x86_64-linux-gnu/libdc1394.so.22 (0x00007f67be927000)
	libv4l1.so.0 => /usr/lib/x86_64-linux-gnu/libv4l1.so.0 (0x00007f67be721000)
	libavcodec.so.54 => /usr/lib/x86_64-linux-gnu/libavcodec.so.54 (0x00007f67bd9cd000)
	libavformat.so.54 => /usr/lib/x86_64-linux-gnu/libavformat.so.54 (0x00007f67bd6ab000)
	libavutil.so.52 => /usr/lib/x86_64-linux-gnu/libavutil.so.52 (0x00007f67bd486000)
	libswscale.so.2 => /usr/lib/x86_64-linux-gnu/libswscale.so.2 (0x00007f67bd23f000)
	libQtOpenGL.so.4 => /usr/lib/x86_64-linux-gnu/libQtOpenGL.so.4 (0x00007f67bcf41000)
	libQtGui.so.4 => /usr/lib/x86_64-linux-gnu/libQtGui.so.4 (0x00007f67bc28e000)
	libQtTest.so.4 => /usr/lib/x86_64-linux-gnu/libQtTest.so.4 (0x00007f67bc069000)
	libQtCore.so.4 => /usr/lib/x86_64-linux-gnu/libQtCore.so.4 (0x00007f67bbb84000)
	libatlas.so.3 => /usr/lib/libatlas.so.3 (0x00007f67bb5f1000)
	libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007f67bb2d7000)
	libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f67bb0b0000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f67bae9e000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f67bac9b000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f67baa95000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f67ba893000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f67ba55e000)
	libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007f67ba347000)
	libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007f67ba142000)
	libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007f67b9f3f000)
	libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007f67b9d3c000)
	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007f67b9b36000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f67b9917000)
	libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007f67b9715000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f67b950f000)
	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f67b9303000)
	libjbig.so.0 => /usr/lib/x86_64-linux-gnu/libjbig.so.0 (0x00007f67b90f5000)
	libIex.so.6 => /usr/lib/x86_64-linux-gnu/libIex.so.6 (0x00007f67b8ed7000)
	libIlmThread.so.6 => /usr/lib/x86_64-linux-gnu/libIlmThread.so.6 (0x00007f67b8cd1000)
	libraw1394.so.11 => /usr/lib/x86_64-linux-gnu/libraw1394.so.11 (0x00007f67b8ac3000)
	libusb-1.0.so.0 => /lib/x86_64-linux-gnu/libusb-1.0.so.0 (0x00007f67b88ac000)
	libv4l2.so.0 => /usr/lib/x86_64-linux-gnu/libv4l2.so.0 (0x00007f67b869e000)
	libxvidcore.so.4 => /usr/lib/x86_64-linux-gnu/libxvidcore.so.4 (0x00007f67b8360000)
	libx264.so.142 => /usr/lib/x86_64-linux-gnu/libx264.so.142 (0x00007f67b7fca000)
	libvpx.so.1 => /usr/lib/x86_64-linux-gnu/libvpx.so.1 (0x00007f67b7beb000)
	libvorbisenc.so.2 => /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2 (0x00007f67b771c000)
	libvorbis.so.0 => /usr/lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007f67b74ef000)
	libtheoraenc.so.1 => /usr/lib/x86_64-linux-gnu/libtheoraenc.so.1 (0x00007f67b72af000)
	libtheoradec.so.1 => /usr/lib/x86_64-linux-gnu/libtheoradec.so.1 (0x00007f67b7096000)
	libspeex.so.1 => /usr/lib/x86_64-linux-gnu/libspeex.so.1 (0x00007f67b6e7d000)
	libschroedinger-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libschroedinger-1.0.so.0 (0x00007f67b6bb9000)
	libopus.so.0 => /usr/lib/x86_64-linux-gnu/libopus.so.0 (0x00007f67b6971000)
	libopenjpeg.so.2 => /usr/lib/x86_64-linux-gnu/libopenjpeg.so.2 (0x00007f67b674f000)
	libmp3lame.so.0 => /usr/lib/x86_64-linux-gnu/libmp3lame.so.0 (0x00007f67b64c2000)
	libgsm.so.1 => /usr/lib/x86_64-linux-gnu/libgsm.so.1 (0x00007f67b62b4000)
	libva.so.1 => /usr/lib/x86_64-linux-gnu/libva.so.1 (0x00007f67b609e000)
	librtmp.so.0 => /usr/lib/x86_64-linux-gnu/librtmp.so.0 (0x00007f67b5e84000)
	libgnutls.so.26 => /usr/lib/x86_64-linux-gnu/libgnutls.so.26 (0x00007f67b5bc6000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f67b59b6000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f67b5713000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f67b5509000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f67b52cd000)
	libaudio.so.2 => /usr/lib/x86_64-linux-gnu/libaudio.so.2 (0x00007f67b50b5000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f67b4dad000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f67b4b5c000)
	libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007f67b4954000)
	libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007f67b4738000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f67b4528000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f67b42ec000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f67b40e8000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f67b3ee2000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f67b3cd1000)
	libv4lconvert.so.0 => /usr/lib/x86_64-linux-gnu/libv4lconvert.so.0 (0x00007f67b3a58000)
	libogg.so.0 => /usr/lib/x86_64-linux-gnu/libogg.so.0 (0x00007f67b384f000)
	liborc-0.4.so.0 => /usr/lib/x86_64-linux-gnu/liborc-0.4.so.0 (0x00007f67b35cd000)
	libgcrypt.so.11 => /lib/x86_64-linux-gnu/libgcrypt.so.11 (0x00007f67b334d000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f67b3139000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f67b2ef7000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f67b2ccd000)
	libXt.so.6 => /usr/lib/x86_64-linux-gnu/libXt.so.6 (0x00007f67b2a67000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f67b2829000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f67b2621000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f67b241c000)
	libcgmanager.so.0 => /lib/x86_64-linux-gnu/libcgmanager.so.0 (0x00007f67b2201000)
	libnih.so.1 => /lib/x86_64-linux-gnu/libnih.so.1 (0x00007f67b1fe9000)
	libnih-dbus.so.1 => /lib/x86_64-linux-gnu/libnih-dbus.so.1 (0x00007f67b1ddf000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f67b1b9a000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f67b1995000)
```

**Comment by jaknap32** [comment]
@CharlesShang hey thanks!, tried it. no luck!

**Comment by jaknap32** [comment]
hey guys thanks!, reinstalled the thole thing in a new ubuntu!, commented out the caffe python path. feels so goods to see both caffe and apollocaffe getting imported finally!!...

**Comment by Russell91** [comment]
Great news!
