### ISSUE TITLE
Assertion Error on custom dataset

### ISSUE THREAD

**Issue by arushk1** [Russell91/ReInspect#32]
I'm facing this issue in training on the Caltech-Pedestrian Dataset : 

`2016-09-20 12:39:15 - GPU device 0
2016-09-20 12:39:47 - Iteration    0 - Train Loss: 0.960499
2016-09-20 12:39:47 - Iteration    0 - Test Loss: 1.13333
2016-09-20 12:39:56 - Iteration  100 - Train Loss: 0.980917
Traceback (most recent call last):
  File "train.py", line 326, in <module>
    main()
  File "train.py", line 323, in main
    train(config)
  File "train.py", line 297, in train
    forward(net, input_gen.next(), config["net"])
  File "train.py", line 37, in load_idl
    target_height=net_config["img_height"])
  File "/home/arush/Workspace/reinspect/utils/__init__.py", line 98, in annotation_jitter
    assert(r.x1 < r.x2 and r.y1 < r.y2)
AssertionError
`

**Comment by Russell91** [comment]
This looks like a label error where x1 >x2.

**Comment by arushk1** [comment]
I checked my data_prep script to make sure x1 is never greater than x2. Same for y1, y2. The error still seems to crop up @Russell91
