### ISSUE TITLE
make train fails -- err msg says "no module named munkres"

### ISSUE THREAD

**Issue by atique81** [Russell91/ReInspect#37]
Dear @Russell91 ,

When I run the command make train, all required data are downloaded nicely, but then it fails throwing the following error message.

Could you please advise what might be going wrong. I have installed all python dependencies for apollocaffe.
.....................................
cd data && tar xf brainwash.tar
Training...
python train.py --config config.json --gpu 0
Traceback (most recent call last):
  File "train.py", line 15, in <module>
    from utils import (annotation_jitter, image_to_h5,
  File "/home/atique/reinspect/utils/__init__.py", line 12, in <module>
    from munkres import Munkres, print_matrix, make_cost_matrix
ImportError: No module named munkres
make: *** [train] Error 1

**Comment by Russell91** [comment]
Please run `pip install munkres`

**Comment by atique81** [comment]
Thank you so much @Russell91 . Why didn't I notice that dependency!!
