### ISSUE TITLE
Layer Convolution has no keyword argument

### ISSUE THREAD

**Issue by Johnson-yue** [Russell91/ReInspect#48]
hi Russell:
       when I made Apollocaffe successfully,  I`m very happy. But then I run #simply.py the error info print, such as this:
`
:~/Deep_Learning/apollocaffe/examples$ cd apollocaffe/
char_model/ cpp/        theano/     
:~/Deep_Learning/apollocaffe/examples$ cd apollocaffe/
:~/Deep_Learning/apollocaffe/examples/apollocaffe$ ls
char_model  cpp  simple.py  theano
:~/Deep_Learning/apollocaffe/examples/apollocaffe$ python simple.py 
Traceback (most recent call last):
  File "simple.py", line 11, in <module>
    net.f(Convolution('conv', (1,1), 1, bottoms=['data']))
  File "/home/yue/Deep_Learning/apollocaffe/python/apollocaffe/layers/caffe_layers.py", line 24, in __init__
    super(Convolution, self).__init__(self, name, kwargs)
  File "/home/yue/Deep_Learning/apollocaffe/python/apollocaffe/layers/layer_headers.py", line 6, in __init__
    self.parse(sublayer, name, kwargs)
  File "/home/yue/Deep_Learning/apollocaffe/python/apollocaffe/layers/layer_headers.py", line 61, in parse
    raise AttributeError('Layer %s has no keyword argument %s=%s' % (param_type, k, v))
## AttributeError: Layer Convolution has no keyword argument kernel_w=1
`
I don`t know why this happpened ??
Please help me~~~~

**Comment by haoli-buaa** [comment]
I met this error too, did you solved it?
