### ISSUE TITLE
make train fails: make: *** [train] Floating point exception (core dumped)

### ISSUE THREAD

**Issue by ujsyehao** [Russell91/ReInspect#54]
Anyone can give me advice about it?

**Comment by ujsyehao** [comment]
![34](https://user-images.githubusercontent.com/17454232/35183577-8783c150-fe23-11e7-971c-a3378bcc623b.png)

**Comment by wolf345** [comment]
2018-03-01 09:55:35 - GPU device 0
Traceback (most recent call last):
  File "train.py", line 294, in <module>
    main()
  File "train.py", line 291, in main
    train(config)
  File "train.py", line 261, in train
    forward(net, input_gen_test.next(), config["net"], False)
  File "train.py", line 35, in load_idl
    target_height=net_config["img_height"])
  File "/home/wolf/Documents/reinspect/apollocaffe-master/reinspect/utils/__init__.py", line 150, in annotation_jitter
    I2[0:(y2 - y1), 0:(x2 - x1), :] = I1[y1:y2, x1:x2, :]
TypeError: slice indices must be integers or None or have an __index__ method
how to solve this problem？
ｔｈａｎｋｓ！

**Comment by ujsyehao** [comment]
@pyupcgithub No, I give up it.
