### ISSUE TITLE
make: *** [train] Error 1

### ISSUE THREAD

**Issue by wolf345** [Russell91/ReInspect#55]
why ?   Ｔｈａｎｋｓ
2018-03-01 09:55:35 - GPU device 0
Traceback (most recent call last):
  File "train.py", line 294, in <module>
    main()
  File "train.py", line 291, in main
    train(config)
  File "train.py", line 261, in train
    forward(net, input_gen_test.next(), config["net"], False)
  File "train.py", line 35, in load_idl
    target_height=net_config["img_height"])
  File "/home/wolf/Documents/reinspect/apollocaffe-master/reinspect/utils/__init__.py", line 150, in annotation_jitter
    I2[0:(y2 - y1), 0:(x2 - x1), :] = I1[y1:y2, x1:x2, :]
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by PumayHui** [comment]
@wolf345 
Change File "/home/wolf/Documents/reinspect/apollocaffe-master/reinspect/utils/init.py", line 145, in 
`
    x1 = max(0, px)
    y1 = max(0, py)
    x2 = min(rescaled_width, target_width - x1)
    y2 = min(rescaled_height, target_height - y1)

    I2[0:(y2 - y1), 0:(x2 - x1), :] = I1[y1:y2, x1:x2, :]
`
to
`  
    x1 = int(max(0, px))
    y1 = int(max(0, py))
    x2 = int(min(rescaled_width, target_width - x1))
    y2 = int(min(rescaled_height, target_height - y1))

    I2[0:int(y2 - y1), 0:int(x2 - x1), :] = I1[y1:y2, x1:x2, :]
`
